customSyntax:
  "postcss-less"

rules:
  # selector-max-type: 0
  declaration-block-single-line-max-declarations: 0

  named-grid-areas-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-no-unknown: true
  function-linear-gradient-no-nonstandard-direction: true
  unit-no-unknown: true
  string-no-newline: true
  custom-property-no-missing-var-function: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-shorthand-property-overrides: true
  block-no-empty: true
  selector-pseudo-class-no-unknown: true
  selector-type-no-unknown: true
  selector-pseudo-element-no-unknown: true
  media-feature-name-no-unknown: true
  at-rule-no-unknown: true
  comment-no-empty: true
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true

  no-invalid-double-slash-comments: true

  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  color-no-invalid-hex: true
  comment-empty-line-before: null
  declaration-block-semicolon-space-before: never
  declaration-empty-line-before: null
  indentation: 4
  max-empty-lines: 2
  no-extra-semicolons: true
  number-leading-zero: never
  number-no-trailing-zeros: true

  color-no-hex: true

  selector-class-pattern: .+
    # - ^\.[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$
    # - resolveNestedSelectors: true

ignoreFiles:
  - '**/*.js'
  - '**/*.ts'
  - '**/*.tsx'
