# NOTE:
# В VS Code нужно выключить родную валидацию:
# "css.validate": false,
# "less.validate": false,
# "scss.validate": false

customSyntax:
  "postcss-less"

rules:
  declaration-block-single-line-max-declarations:
    - 0
    - severity: warning

  selector-max-type:
    - 0
    # - ignore:
    #   - child
    #   - compounded
    #   - custom-elements
    #   - descendant
    #   - next-sibling

  at-rule-no-unknown: true
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  block-no-empty: true
  color-function-notation: modern
  color-named: never
  color-no-hex: true
  color-no-invalid-hex: true
  # comment-empty-line-before: always
  comment-no-empty: true
  custom-property-no-missing-var-function: true
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-space-before: never
  # declaration-empty-line-before: null
  declaration-no-important: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  function-no-unknown: true
  indentation: 4
  max-empty-lines: 2
  media-feature-name-no-unknown: true
  named-grid-areas-no-invalid: true
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  number-leading-zero: never
  number-no-trailing-zeros: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  string-no-newline: true
  unit-no-unknown: true

  selector-class-pattern: .+
    # - ^\.[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$
    # - resolveNestedSelectors: true

ignoreFiles:
  - '**/*.js'
  - '**/*.ts'
  - '**/*.tsx'
